### ISSUE TITLE
Reduce-reducers

### ISSUE THREAD

**Issue by brianleonard15** [davidkpiano/react-redux-form#613]
Hi,

How could I achieve a store structure like this so that I can store some page specific state outside of the form model, but not under its own key:
```
someOtherState: ...
myReduxFormPage: 
    count: 2
    someOtherPageSpecificState: "notImportant"
    model:  {the form model}
    form:  {the form}
```

Not this:
```
someOtherState: ...
myReduxFormPage: 
    otherPageState: {count: 2, someOtherPageSpecificState: "notImportant"}
    model:  {the form model}
    form:  {the form}
```

What I've got so far:
```js
// RootReducer.js
const rootReducer = combineReducers({
  someOtherState: someOtherStateReducer, 
  myReduxFormPage: myReduxFormPageReducer,
});

// myReduxFormPageReducer

const reducer = (state = {count: 0}, action) => {
  switch (action.type) {
    case INCREASE_COUNT:
      return {...state, count: action.newCount};
    default:
      return state;
  }
};

const MyReduxFormPageReducer =
  reduceReducers(
    reducer,
    combineReducers({
      'model': modelReducer('model', {}),
      'form': formReducer('myReduxFormPage.model', {})
    }),
)
```
